#!/bin/sh
### BEGIN INIT INFO
# Provides:          firstboot_custom
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Run custom first boot tasks
# Description:       This script runs custom commands on first boot and then removes itself.
### END INIT INFO

case "$1" in
start)
    echo "Running custom first boot tasks..."
    # Place your custom commands here, for example:
    BOOTCONF="/tmp/bootconf.txt"
    echo '[all]' >"$BOOTCONF"
    echo "BOOT_UART=1" >>"$BOOTCONF"
    echo "POWER_OFF_ON_HALT=1" >>"$BOOTCONF"
    echo "PSU_MAX_CURRENT=5000" >>"$BOOTCONF"
    rpi-eeprom-config --apply "$BOOTCONF"

    # Remove this script from startup
    update-rc.d config-eeprom-once remove
    rm -f /etc/init.d/config-eeprom-once
    ;;
*)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
