services:
  sensos-controller:
    build: ./controller
    container_name: sensos-controller
    restart: always
    depends_on:
      - sensos-database
      - sensos-wireguard
      - sensos-registry
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      WG_IP: ${WG_IP}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - sensos_wireguard_config:/config
      - sensos_controller_wg_dir:/etc/wireguard
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${API_PORT:-8000}:8000"
      - "${REGISTRY_PORT:-5000}:5000"
    networks:
      - sensos_network

  sensos-wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: sensos-wireguard
    restart: unless-stopped
    env_file: .env
    cap_add:
      - NET_ADMIN
    environment:
      - LOG_CONFS=true
    volumes:
      - sensos_wireguard_config:/config
    ports:
      - "${WG_PORT:-51820}:51820/udp"
    healthcheck:
      test: ["CMD", "wg", "show"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - sensos_network

  sensos-database:
    build: ./database
    container_name: sensos-database
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sensos_database:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - sensos_network

  sensos-registry:
    image: registry:2
    container_name: sensos-registry
    restart: always
    env_file: .env
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
    volumes:
      - sensos_registry:/var/lib/registry
    ports:
      - "5000"
    networks:
      - sensos_network

volumes:
  sensos_database:
    name: sensos_database
  sensos_wireguard_config:
    name: sensos_wireguard_config
  sensos_controller_wg_dir:
    name: sensos_controller_wg_dir
  sensos_registry:
    name: sensos_registry

networks:
  sensos_network:
    driver: bridge
