services:
  sensos-database:
    build: ./database
    container_name: sensos-database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sensos_database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sensos"]
      interval: 10s
      retries: 5
      start_period: 5s

  sensos-controller:
    build: ./controller
    container_name: sensos-controller
    restart: always
    depends_on:
      - sensos-database
      - wireguard
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    cap_add:
      - NET_ADMIN
    volumes:
      - wireguard_config:/etc/wireguard
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - LOG_CONFS=true
    volumes:
      - wireguard_config:/config
    ports:
      - "51820:51820/udp"
    healthcheck:
      test: ["CMD", "wg", "show"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  sensos_database:
  wireguard_config:
