services:
  sensos-database:
    build: ./database
    container_name: sensos-database
    restart: always
    environment:
      POSTGRES_DB: sensos
      POSTGRES_USER: sensos
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sensos_database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sensos"]
      interval: 10s
      retries: 5
      start_period: 5s

  sensos-controller:
    build: ./controller
    container_name: sensos-controller
    restart: always
    depends_on:
      - sensos-database
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    cap_add:
      - NET_ADMIN
    ports:
      - "51820:51820/udp"

volumes:
  sensos_database:
