services:
  sensos-client-database:
    build: ./database
    container_name: sensos-client-database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sensos-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  sensos-client-sound-capture:
    build: ./sound_capture
    container_name: sensos-client-sound-capture
    restart: always
    depends_on:
      - sensos-client-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      AUDIO_SOURCE: ${AUDIO_SOURCE}
      AUDIO_DEVICE: ${AUDIO_DEVICE}
      RECORD_DURATION: ${RECORD_DURATION}
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - "audio"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  sensos-client-birdnet:
    build: ./birdnet
    container_name: sensos-client-birdnet
    restart: always
    depends_on:
      - sensos-client-database
      - sensos-client-sound-capture
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  sensos-db-data:
