services:
  sensos-client-database:
    image: sensos-client-database
    container_name: sensos-client-database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  sensos-client-catalog-audio:
    image: sensos-client-catalog-audio
    container_name: sensos-client-catalog-audio
    restart: always
    depends_on:
      - sensos-client-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - /sensos/data/audio_recordings:/audio_recordings

  sensos-client-birdnet:
    image: sensos-client-birdnet
    container_name: sensos-client-birdnet
    restart: always
    depends_on:
      - sensos-client-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NUMBA_CACHE_DIR: /tmp/numba_cache
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      LATITUDE: ${LATITUDE}
      LONGITUDE: ${LONGITUDE}
    volumes:
      - /sensos/data/audio_recordings:/audio_recordings
      - ./birdnet/model:/model

  sensos-client-db-manager:
    image: sensos-client-db-manager
    container_name: sensos-client-db-manager
    restart: always
    depends_on:
      - sensos-client-database
    environment:
      BIRDNET_SCORE_THRESHOLD: ${BIRDNET_SCORE_THRESHOLD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - /sensos/data/audio_recordings:/audio_recordings

  sensos-client-sqlite-importer:
    image: sensos-client-sqlite-importer
    container_name: sensos-client-sqlite-importer
    restart: always
    depends_on:
      - sensos-client-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - /sensos/data/microenv:/microenv

  sensos-system-recorder:
    image: sensos-client-system-recorder
    container_name: sensos-client-system-recorder
    restart: always
    depends_on:
      - sensos-client-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
      - /sensos/data:/sensos/data:ro

  sensos-system-reporter:
    image: sensos-client-system-reporter
    container_name: sensos-client-system-reporter
    restart: no
    depends_on:
      - sensos-client-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - /sensos:/sensos:ro
    entrypoint: ["python3", "reporter.py"]
