services:
  sensos-client-database:
    build: ./database
    container_name: sensos-client-database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sensos
    volumes:
      - sensos-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  sensos-client-sound-capture:
    build: ./sound_capture
    container_name: sensos-client-sound-capture
    restart: always
    depends_on:
      - sensos-client-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sensos
      DB_HOST: sensos-client-database
      DB_PORT: 5432
      AUDIO_SOURCE: default
      RECORD_DURATION: 0
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  sensos-client-birdnet:
    build: ./birdnet
    container_name: sensos-client-birdnet
    restart: always
    depends_on:
      - sensos-client-database
      - sensos-client-sound-capture
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sensos
      DB_HOST: sensos-client-database
      DB_PORT: 5432
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  sensos-db-data:
